[program:mitabl-queue-worker]
command=php /app/artisan queue:work redis --sleep=1 --tries=3 --max-time=3600 --queue=crm-escalations,crm-communications,default
process_name=%(program_name)s_%(process_num)02d
numprocs=2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
stdout_logfile=/var/log/mitabl/queue-worker.log
stderr_logfile=/var/log/mitabl/queue-worker-error.log
