// IMPORTANT: This file is auto-generated by `flutterfire configure`.
//
// DO NOT edit it manually.
// DO NOT commit this file to source control if it contains real secrets.
// It is listed in .gitignore by flutterfire.
//
// ─── How to generate this file ───────────────────────────────────────────────
//
// 1. Install the FlutterFire CLI (once per machine):
//      dart pub global activate flutterfire_cli
//
// 2. Log in to Firebase:
//      firebase login
//
// 3. Run from the mobile-app root:
//      flutterfire configure --project=<your-firebase-project-id>
//
// Choose the platforms you support (android + ios at minimum).
// flutterfire will download google-services.json and GoogleService-Info.plist
// into the correct locations AND regenerate this file automatically.
//
// ─────────────────────────────────────────────────────────────────────────────
//
// This placeholder exists so the Dart compiler does not error on the
//   import 'firebase_options.dart'   line in main.dart
// before the real file is generated.
//
// Replace this entire file by running `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'firebase_options.dart has not been generated yet.\n'
      'Run: flutterfire configure --project=<your-firebase-project-id>',
    );
  }
}
